import React from 'react';
import { ExternalLink, MonitorCog, ShieldCheck } from 'lucide-react';
import './access-guide.css';

export default function AccessGuide({ demo }: { demo: boolean }) {
  const [loading, setLoading] = React.useState<'accessibility' | 'screen-recording' | null>(null); const [error, setError] = React.useState('');
  async function open(pane: 'accessibility' | 'screen-recording') { if (demo) return; setLoading(pane); setError(''); try { const response = await fetch('/api/access/settings', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ pane }) }); if (!response.ok) throw Error(); } catch { setError('The system settings pane could not be opened. Open macOS System Settings manually.'); } finally { setLoading(null); } }
  return <section className="access-guide" aria-label="Computer access guide"><header><span className="usage-kicker">COMPUTER ACCESS</span><h2>Enable browser and desktop access</h2><p>Installed tools, operating-system permission, and a successful computer-use action are separate checks.</p></header><div className="access-guide-grid"><article><span className="access-guide-icon"><MonitorCog size={18} /></span><div><h3>Codex browser and apps</h3><p>In Codex, open Plugins → Computer Use and install or enable its server and skill. Then use Settings → Computer use to manage the browser and always-allowed apps. HQ can use a connected Chrome extension; Codex’s embedded browser may be unavailable to this standalone runtime.</p><a href="https://learn.chatgpt.com/docs/computer-use" target="_blank" rel="noreferrer">Open the official Codex guide <ExternalLink size={13} /></a></div></article><article><span className="access-guide-icon"><ShieldCheck size={18} /></span><div><h3>macOS permission</h3><p>Grant Codex Computer Use Accessibility and Screen Recording in macOS. macOS must approve these permissions manually; file or network access does not grant control of desktop apps.</p><div className="access-guide-actions"><button className="small-button" onClick={() => open('accessibility')} disabled={demo || loading !== null}>{loading === 'accessibility' ? 'Opening…' : 'Open Accessibility settings'}</button><button className="small-button" onClick={() => open('screen-recording')} disabled={demo || loading !== null}>{loading === 'screen-recording' ? 'Opening…' : 'Open Screen Recording settings'}</button></div></div></article></div>{error && <p className="access-guide-error" role="alert">{error}</p>}{demo && <p className="access-guide-note">Demo mode does not open system settings.</p>}<details className="claude-access"><summary>Using Claude Desktop instead?</summary><p>In Claude Desktop, use Settings → General → Computer use, then grant the same macOS permissions. Claude asks for approval for each app session. Company HQ’s Claude execution adapter is still unavailable.</p></details></section>;
}
