import React from 'react';
import { ExternalLink, MonitorCog, ShieldCheck } from 'lucide-react';
import './access-guide.css';

export default function AccessGuide({ demo }: { demo: boolean }) {
  const [loading, setLoading] = React.useState<'accessibility' | 'screen-recording' | null>(null); const [error, setError] = React.useState('');
  async function open(pane: 'accessibility' | 'screen-recording') { if (demo) return; setLoading(pane); setError(''); try { const response = await fetch('/api/access/settings', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ pane }) }); if (!response.ok) throw Error(); } catch { setError('The system settings pane could not be opened. Open macOS System Settings manually.'); } finally { setLoading(null); } }
  return <section className="access-guide" aria-label="Computer access guide"><header><span className="usage-kicker">COMPUTER ACCESS</span><h2>Enable browser and desktop access</h2><p>Start with a connected provider. Add computer access only when a task needs to use a browser or another app.</p></header><div className="access-guide-grid"><article><span className="access-guide-icon"><MonitorCog size={18} /></span><div><h3>Codex browser and apps</h3><p>In Codex, open Plugins → Computer Use and install or enable its server and skill. Then use Settings → Computer use to manage the browser and always-allowed apps. HQ can use a connected Chrome extension; Codex’s embedded browser may be unavailable to this standalone runtime.</p><a href="https://learn.chatgpt.com/docs/computer-use" target="_blank" rel="noreferrer">Open the official Codex guide <ExternalLink size={13} /></a></div></article><article><span className="access-guide-icon"><ShieldCheck size={18} /></span><div><h3>macOS permission</h3><p>In System Settings → Privacy & Security, enable the helper named in the permission prompt (for Codex, Codex Computer Use). If it is missing from the list, first enable Computer Use in Codex and ask it to inspect an app; that triggers macOS registration. Restart the requesting helper if macOS asks. Company HQ itself does not need blanket disk or screen access just to chat.</p><div className="access-guide-actions"><button className="small-button" onClick={() => open('accessibility')} disabled={demo || loading !== null}>{loading === 'accessibility' ? 'Opening…' : 'Open Accessibility settings'}</button><button className="small-button" onClick={() => open('screen-recording')} disabled={demo || loading !== null}>{loading === 'screen-recording' ? 'Opening…' : 'Open Screen Recording settings'}</button></div></div></article></div>{error && <p className="access-guide-error" role="alert">{error}</p>}{demo && <p className="access-guide-note">Demo mode does not open system settings.</p>}<details className="claude-access"><summary>Other models, images, and desktop access</summary><p>A model that understands an image does not automatically have mouse or keyboard tools. HQ uses the tools exposed by the selected provider. Claude Desktop permissions stay with Claude Desktop; Kimi and GLM do not inherit Codex’s browser tools. Check Workspace tools for this chat before requesting computer work. Image attachments stay with your selected provider; HQ will ask you to choose a supported model instead of silently switching accounts.</p></details></section>;
}
