import React from 'react';
import { Brain, Check, ChevronRight, CircleAlert, Code2, Cpu, ExternalLink, PlugZap, RefreshCw, X } from 'lucide-react';
import RuntimeTools from './RuntimeTools';
import AccessGuide from './AccessGuide';
import UsagePanel, { type UsageWindow } from './UsagePanel';

type Data = Record<string, any>;
type Provider = { id: string; label?: string; installed?: boolean; cliInstalled?: boolean; desktopInstalled?: boolean; runtimeReady?: boolean; authentication?: string; reason?: string; helpUrl?: string; activity?: { message?: string; status?: string; time?: string }[]; models?: string[]; usageWindows?: UsageWindow[]; message?: string; authUrl?: string };
type Props = { health: Data; runtime: Data; events?: Data[]; onRefresh: () => Promise<void>; onModels: () => void };
const supported = new Set(['codex', 'claude', 'kimi', 'zai', 'cursor', 'grok', 'ollama']);
function safeAuthUrl(url?: string) { try { const value = new URL(url || ''); const hosts = new Set(['auth.openai.com', 'chatgpt.com', 'auth0.openai.com']); return value.protocol === 'https:' && !value.username && !value.password && !value.port && hosts.has(value.hostname) ? value.href : ''; } catch { return ''; } }
function status(provider: Provider) { if (!provider.installed) return 'Not installed'; if (provider.authentication === 'signed_in') return 'Signed in'; if (provider.authentication === 'signing_in') return 'Sign-in in progress'; if (provider.authentication === 'sign_in_required') return 'Sign in required'; return provider.runtimeReady ? 'Runtime ready' : 'Status not checked'; }
function toolActivity(events: Data[], tool: string) { const terms = tool === 'rufloMemory' ? ['ruflo', 'memory'] : ['codebase', 'code']; return events.filter(event => { const reported = String(event.data?.tool || '').toLowerCase(); return (event.type === 'tool.started' || event.type === 'tool.completed') && terms.some(term => reported.includes(term)); }).slice(-8).reverse(); }

export default function Connections({ health, runtime, events = [], onRefresh, onModels }: Props) {
  const [providers, setProviders] = React.useState<Provider[]>([]), [checked, setChecked] = React.useState<Date | null>(null), [refreshing, setRefreshing] = React.useState(false), [error, setError] = React.useState(''), [selected, setSelected] = React.useState<Provider | null>(null), [selectedTool, setSelectedTool] = React.useState<string | null>(null);
  const dialogRef = React.useRef<HTMLDialogElement>(null); const caps = health?.capabilities || {};
  const tools = [{ id: 'rufloMemory', name: 'Shared memory', description: 'Keeps useful decisions organized for each project.', icon: Brain }, { id: 'codebaseMemory', name: 'Code understanding', description: 'Helps agents navigate code when a project is attached.', icon: Code2 }];
  const loadProviders = React.useCallback(async (checkCodex = false) => { const response = await fetch('/api/providers'), data = await response.json().catch(() => ({})); if (!response.ok) throw Error(data.error || 'Could not load provider status.'); let list = Array.isArray(data.providers) ? data.providers : []; if (checkCodex && health?.mode !== 'demo' && list.some((provider: Provider) => provider.id === 'codex' && provider.installed)) { const result = await fetch('/api/providers/codex/check', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: '{}' }); if (result.ok) { const update = await result.json(); list = list.map((provider: Provider) => provider.id === 'codex' ? { ...provider, ...update } : provider); } else { list = list.map((provider: Provider) => provider.id === 'codex' ? { ...provider, usageWindows: [], authentication: 'not_checked', message: 'Codex status could not be checked.' } : provider); } } setProviders(list); setChecked(new Date(data.checkedAt || Date.now())); }, [health?.mode]);
  React.useEffect(() => { loadProviders(true).catch((e: Error) => setError(e.message)); }, [loadProviders]); React.useEffect(() => { if (selected) dialogRef.current?.showModal(); else dialogRef.current?.close(); }, [selected]);
  async function refresh() { setRefreshing(true); setError(''); try { await Promise.all([onRefresh(), loadProviders(true)]); } catch (e: any) { setError(e.message || 'Could not check setup.'); } finally { setRefreshing(false); } }
  async function action(action: 'connect' | 'check' | 'open' | 'cancel') { if (!selected || !supported.has(selected.id) || health?.mode === 'demo') return; setRefreshing(true); setError(''); try { const response = await fetch(`/api/providers/${selected.id}/${action}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: '{}' }), data = await response.json().catch(() => ({})); if (!response.ok) throw Error(data.error || 'Provider action failed.'); setSelected({ ...selected, ...data }); await loadProviders(false); } catch (e: any) { setError(e.message || 'Provider action failed.'); } finally { setRefreshing(false); } }
  const codex = providers.find(provider => provider.id === 'codex');
  return <div className="connections-view"><header><span className="eyebrow">SETTINGS</span><h1>Connections and allowance</h1><p>See the provider status for this device and the usage signals it reports. A connection does not start a model turn.</p></header>
    <section className="connection-engine"><div className="engine-tile"><Cpu size={24} /></div><div><h2>Codex</h2><p>{codex ? status(codex) : runtime.connected ? 'Connected in this chat' : 'Provider status is loading'}</p></div><span className={`setup-badge ${codex?.authentication === 'signed_in' ? 'ok' : ''}`}>{codex ? status(codex) : 'Checking'}</span></section>
    <button className="supervisor-setting" onClick={onModels}><span><b>Supervisor model</b><small>{runtime.model || 'Automatic · reviewed model selection'}</small></span><span>Choose model<ChevronRight size={15} /></span></button>
    <UsagePanel runtime={runtime} account={codex} />
    <div className="connections-heading"><h2>Providers</h2><span>Click a provider for its status and actions</span></div><div className="provider-cards">{providers.map(provider => <button className="provider-card" key={provider.id} onClick={() => setSelected(provider)}><span className="provider-monogram">{(provider.label || provider.id).slice(0, 1)}</span><span><b>{provider.label || provider.id}</b><small>{status(provider)}</small></span><span className={`setup-badge ${provider.authentication === 'signed_in' ? 'ok' : ''}`}>{provider.runtimeReady ? 'Ready' : provider.desktopInstalled ? 'Desktop installed' : provider.cliInstalled ? 'CLI installed' : 'Unavailable'}</span><ChevronRight size={16} /></button>)}</div>
    <RuntimeTools team={runtime.team} connected={runtime.connected}/>
    <div className="connections-heading"><h2>Workspace tools</h2><span>Click for reported activity</span></div><div className="connection-tools">{tools.map(({ id, name, description, icon: Icon }) => { const activity = toolActivity(events, id); return <article key={id} className={selectedTool === id ? 'is-open' : ''}><button onClick={() => setSelectedTool(selectedTool === id ? null : id)}><span className="tool-tile"><Icon size={20} /></span><span><h3>{name}</h3><p>{description}</p></span><span className={`setup-badge ${caps[id]?.available ? 'ok' : ''}`}>{caps[id]?.available ? <><Check size={12} />Installed</> : 'Unavailable'}</span></button>{selectedTool === id && <div className="tool-activity"><b>Reported activity</b>{activity.length ? activity.map((event, index) => <p key={index}>{event.type === 'tool.completed' ? 'Completed' : 'Started'} · {event.data?.tool}</p>) : <p>Not reported.</p>}</div>}</article>; })}</div>
    <AccessGuide demo={health?.mode === 'demo'}/>
    <section className="provider-note"><PlugZap size={19} /><div><h3>Allowance scope</h3><p>Individual agent allowance: Not reported. Account windows can overlap, so Company HQ does not add them together or treat them as per-agent quotas.</p></div></section>
    {error && <p className="connection-error" role="alert"><CircleAlert size={15} />{error}</p>}<footer className="setup-footer"><span>{checked ? `Provider status checked · ${checked.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}` : 'Checking provider status…'}</span><button onClick={refresh} disabled={refreshing}><RefreshCw size={13} className={refreshing ? 'refreshing' : ''} />{refreshing ? 'Checking…' : 'Check again'}</button></footer>
    <dialog className="provider-dialog" ref={dialogRef} onCancel={() => setSelected(null)} onClick={event => { if (event.target === dialogRef.current) setSelected(null); }}>{selected && <><button className="provider-dialog-close" aria-label="Close provider details" onClick={() => setSelected(null)}><X size={18} /></button><span className="eyebrow">PROVIDER CONNECTION</span><h2>{selected.label || selected.id}</h2><p>{selected.message || selected.reason || 'Provider status is reported by the local runtime.'}</p>{error && <p className="connection-error" role="alert"><CircleAlert size={15} />{error}</p>}<dl><div><dt>Desktop app</dt><dd>{selected.desktopInstalled ? 'Installed' : 'Not installed'}</dd></div><div><dt>Adapter</dt><dd>{selected.runtimeReady ? 'Runtime ready' : 'HQ execution adapter unavailable'}</dd></div><div><dt>Authentication</dt><dd>{status(selected)}</dd></div><div><dt>Models</dt><dd>{selected.models?.length ? selected.models.join(', ') : 'Not reported'}</dd></div></dl>{selected.id === 'codex' && <UsagePanel account={selected} compact />}<div className="provider-activity"><h3>Recent activity</h3>{selected.activity?.length ? <ul>{selected.activity.slice().reverse().map((item, index) => <li key={index}>{item.message || item.status || 'Provider activity reported'}<small>{item.time ? new Date(item.time).toLocaleString() : ''}</small></li>)}</ul> : <p>Not reported.</p>}</div><footer>{selected.authentication === 'signing_in' && <button className="small-button" onClick={() => action('cancel')} disabled={refreshing || health?.mode === 'demo'}>Cancel sign-in</button>}{selected.id === 'codex' && selected.authentication !== 'signed_in' && <button className="primary-button" onClick={() => action('connect')} disabled={refreshing || health?.mode === 'demo'}>{refreshing ? 'Working…' : 'Begin sign-in'}</button>}{selected.id === 'codex' && <button className="small-button" onClick={() => action('check')} disabled={refreshing || health?.mode === 'demo'}>Check status</button>}{selected.desktopInstalled && selected.id !== 'codex' && <button className="small-button" onClick={() => action('open')} disabled={refreshing || health?.mode === 'demo'}>Open provider app</button>}{safeAuthUrl(selected.authUrl) && <a className="primary-button" href={safeAuthUrl(selected.authUrl)} target="_blank" rel="noreferrer">Continue sign-in <ExternalLink size={14} /></a>}{selected.helpUrl && <a className="small-button" href={selected.helpUrl} target="_blank" rel="noreferrer">Provider help <ExternalLink size={13} /></a>}</footer></>}</dialog>
  </div>;
}
