import React,{useEffect,useState} from 'react';
import {Sparkles} from 'lucide-react';
type Data=Record<string,any>;
export default function ModelPicker({models,model,provider,runtime,demo,onChoose,onSettings}:{models:string[];model:string;provider:string;runtime:Data;demo:boolean;onChoose:(provider:string,model:string)=>void;onSettings:()=>void}){
  const [providers,setProviders]=useState<Data[]>([]),[tab,setTab]=useState((runtime.providerBound||runtime.threadId)?runtime.provider||provider:provider),[error,setError]=useState(''),[checking,setChecking]=useState(false);
  useEffect(()=>{let active=true;fetch('/api/providers').then(r=>r.json()).then(value=>{if(active)setProviders(value.providers||[])}).catch(()=>{if(active)setError('Provider status could not be loaded.')});return()=>{active=false}},[]);
  async function check(){setChecking(true);setError('');try{const r=await fetch(`/api/providers/${tab}/check`,{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});const d=await r.json();if(!r.ok)throw Error(d.error||'Connection could not be checked.');setProviders(rows=>rows.map(row=>row.id===tab?{...row,...d}:row))}catch(e:any){setError(e.message)}finally{setChecking(false)}}
  useEffect(()=>{if(!demo&&providers.some(p=>p.id===tab&&p.installed)&&['codex','claude','kimi','zai','deepseek','openai-compatible'].includes(tab)) void check();},[tab,demo,providers.length]);
  const row=providers.find(p=>p.id===tab),ids=tab==='codex'?['auto',...models]:row?.authentication==='signed_in'?(row.models||[]):[];
  const info:Record<string,string[]>={auto:['Automatic','Astra supervises · smaller workers when useful'],'gpt-6-astra':['GPT 6 Astra','Architecture, planning and demanding problems'],'gpt-5.6-sol':['GPT 5.6 Sol','Complex reasoning and independent reviews'],'gpt-5.6-terra':['GPT 5.6 Terra','Everyday building and fixes'],'gpt-5.6-luna':['GPT 5.6 Luna','Small, bounded tasks'],'gpt-5.5':['GPT 5.5','General purpose']};
  return <><span className="eyebrow">YOUR ENGINE</span><h2>Choose a model</h2><p>{(runtime.providerBound||runtime.threadId)?'This chat keeps its provider and model. Start a new chat to change them.':'Choose the supervisor. It assigns useful work to smaller capable agents when the runtime supports teams.'}</p>
    <div className="provider-model-tabs" role="tablist" aria-label="Model providers">{(providers.length?providers:[{id:'codex',label:'Codex'}]).map(p=><button role="tab" aria-selected={tab===p.id} className={`small-button ${tab===p.id?'chosen':''}`} onClick={()=>setTab(p.id)} key={p.id}>{p.label||p.id}</button>)}</div>
    {tab==='claude'&&<p className="model-caveat">Claude uses your Claude Code account and its native permissions. Workspace mode is not an operating-system filesystem sandbox.</p>}
    {tab==='openai-compatible'&&<p className="model-caveat">Custom API models can chat about a project. This adapter has no file editing, browser, computer use, worker or image tools.</p>}
    {['codex','claude','kimi','zai','deepseek','openai-compatible'].includes(tab)&&<button className="small-button" disabled={checking||demo} onClick={check}>{checking?'Checking…':'Check connection & models'}</button>}
    <div className="model-options">{ids.map((id:string)=>{const detail=info[id]||[row?.modelDetails?.find((d:Data)=>d.value===id)?.displayName||id,tab==='codex'?'Reviewed Codex model':'Reported by the connected runtime'];const chosen=((runtime.providerBound||runtime.threadId)?runtime.provider||provider:provider)===tab&&(runtime.model||model)===id;return <button key={id} className={chosen?'chosen':''} disabled={!!(runtime.providerBound||runtime.threadId)||demo} onClick={()=>onChoose(tab,id)}><span className="model-glyph"><Sparkles size={16}/></span><span><b>{detail[0]}</b><small>{detail[1]}</small></span><i>{chosen?'Selected':row?.label||tab}</i></button>})}</div>
    {!ids.length&&<div className="provider-note"><p>{row?.message||(['codex','claude','kimi','zai','deepseek','openai-compatible'].includes(tab)?'Check the connection or sign in to load the models available to this account.':'This provider is detected, but HQ does not yet have a verified execution adapter for it.')}</p><button className="small-button" onClick={onSettings}>Open provider connections</button></div>}
    {error&&<p role="alert">{error}</p>}<p className="model-caveat">Each provider keeps its own account, tools and allowance. Automatic continuation uses only the models enabled in routing settings.</p></>
}
