import React from 'react';
import { ChevronRight, CircleAlert, ExternalLink, LoaderCircle, Search, X } from 'lucide-react';
import './native-tasks.css';

type ProviderId = 'codex' | 'claude' | 'kimi' | 'zai' | 'cursor' | 'grok' | 'ollama';
type Task = { id: string; title?: string; project?: string; updatedAt?: string | number; status?: string; source?: string; summary?: string };
type Result = { provider?: string; readOnly?: boolean; tasks?: Task[]; nextCursor?: string | null };
const providers: { id: ProviderId; label: string }[] = [{ id: 'codex', label: 'Codex' }, { id: 'claude', label: 'Claude' }, { id: 'kimi', label: 'Kimi' }, { id: 'zai', label: 'Z.ai' }, { id: 'cursor', label: 'Cursor' }, { id: 'grok', label: 'Grok' }, { id: 'ollama', label: 'Ollama' }];
function taskTime(value?: string | number) { const milliseconds = typeof value === 'number' && value < 10_000_000_000 ? value * 1000 : value; const date = new Date(milliseconds || ''); return Number.isNaN(date.getTime()) ? 'Updated time not reported' : `Updated ${date.toLocaleString([], { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' })}`; }

export default function NativeTasks({ demo }: { demo: boolean }) {
  const [provider, setProvider] = React.useState<ProviderId>('codex'); const [query, setQuery] = React.useState(''); const [archived, setArchived] = React.useState(false); const [includeAgents, setIncludeAgents] = React.useState(false); const [loadedQuery, setLoadedQuery] = React.useState<string | null>(null); const [tasks, setTasks] = React.useState<Task[]>([]); const [cursor, setCursor] = React.useState<string | null>(null); const [loading, setLoading] = React.useState(false); const [error, setError] = React.useState(''); const [selected, setSelected] = React.useState<Task | null>(null); const request = React.useRef(0); const mounted = React.useRef(true);
  React.useEffect(() => () => { mounted.current = false; request.current += 1; }, []); React.useEffect(() => { request.current += 1; setLoading(false); if(provider!=='codex'&&archived)setArchived(false); setTasks([]); setCursor(null); setLoadedQuery(null); setError(''); setSelected(null); }, [provider, archived, includeAgents]);
  React.useEffect(() => { if (loadedQuery !== null && query.trim() !== loadedQuery) { request.current += 1; setLoading(false); setTasks([]); setCursor(null); setLoadedQuery(null); setSelected(null); setError(''); } }, [query, loadedQuery]);
  async function load(next = false) { if (demo || !['codex','claude'].includes(provider) || loading) return; const current = ++request.current; const search = next ? loadedQuery || '' : query.trim(); setLoading(true); setError(''); if (!next) { setTasks([]); setCursor(null); setSelected(null); } try { const params = new URLSearchParams({ search, archived: String(archived), includeAgents: String(includeAgents) }); if (next && cursor) params.set('cursor', cursor); const response = await fetch(`/api/providers/${provider}/tasks?${params}`); const data: Result = await response.json().catch(() => ({})); if (!response.ok) throw Error('Provider tasks could not be loaded.'); if (current !== request.current || !mounted.current) return; setTasks(previous => next ? [...previous, ...(data.tasks || []).filter(task => !previous.some(item => item.id === task.id))] : data.tasks || []); setCursor(data.nextCursor || null); setLoadedQuery(search); } catch { if (current === request.current && mounted.current) setError('Provider tasks could not be loaded. Try again.'); } finally { if (current === request.current && mounted.current) setLoading(false); } }
  async function openTask(task: Task) { if (demo || !['codex','claude'].includes(provider)) return; const current = ++request.current; setLoading(true); setError(''); try { const response = await fetch(`/api/providers/${provider}/tasks/${encodeURIComponent(task.id)}`); const data = await response.json().catch(() => ({})); if (!response.ok) throw Error('Task details could not be loaded.'); if (current === request.current) setSelected(data.task || task); } catch { if (current === request.current) setError('Task details could not be loaded. Try again.'); } finally { if (current === request.current) setLoading(false); } }
  async function openProvider() { if (demo || provider === 'codex') return; setLoading(true); setError(''); try { const response = await fetch(`/api/providers/${provider}/open`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: '{}' }); if (!response.ok) throw Error(); } catch { setError('The provider app could not be opened. Check that its desktop app is installed.'); } finally { setLoading(false); } }
  return <section className="native-tasks" aria-label="Provider tasks"><header><div><span className="usage-kicker">READ-ONLY PROVIDER METADATA</span><h2>Provider tasks</h2><p>Browse task summaries from your connected provider. This does not resume or copy conversations.</p></div></header><div className="native-task-tabs" role="tablist" aria-label="Provider"><>{providers.map(item => <button key={item.id} role="tab" aria-selected={provider === item.id} onClick={() => setProvider(item.id)}>{item.label}</button>)}</></div>
    {demo ? <p className="native-tasks-note">Provider task browsing is disabled in demo mode.</p> : !['codex','claude'].includes(provider) ? <div className="native-tasks-note"><b>{providers.find(item => item.id === provider)?.label} needs an adapter</b><p>Company HQ cannot browse this provider’s tasks until its native adapter is verified.</p><button className="small-button" onClick={openProvider} disabled={loading}>Open provider app <ExternalLink size={13} /></button></div> : <><div className="native-task-controls"><label><Search size={15} /><input value={query} onChange={event => setQuery(event.target.value)} onKeyDown={event => { if (event.key === 'Enter') load(); }} placeholder="Filter task summaries" aria-label="Search provider tasks" /></label><button className="primary-button" onClick={() => load()} disabled={loading}>{loading ? <LoaderCircle className="refreshing" size={15} /> : <Search size={15} />}{loadedQuery === null ? 'Load tasks' : 'Search'}</button></div><div className="native-task-filters"><label><input type="checkbox" disabled={provider!=='codex'} checked={archived} onChange={event => setArchived(event.target.checked)} />Archived</label><label><input type="checkbox" checked={includeAgents} onChange={event => setIncludeAgents(event.target.checked)} />Include agents</label></div>{error && <p className="native-tasks-error" role="alert"><CircleAlert size={15} />{error}</p>}{loadedQuery === null ? <p className="native-tasks-empty">Select Load tasks to request read-only metadata. Claude filtering applies to each loaded page; its SDK does not report task liveness.</p> : !loading && !tasks.length ? <p className="native-tasks-empty">No matching task summaries were reported.</p> : <div className="native-task-list">{tasks.map(task => <button key={task.id} className="native-task-row" onClick={() => openTask(task)}><span><b>{task.title || 'Untitled task'}</b><small title={task.project || undefined}>{task.project?.split(/[\\/]/).filter(Boolean).pop() || 'No project reported'} · {taskTime(task.updatedAt)}</small></span><em>{task.status || 'Status not reported'}</em><ChevronRight size={15} /></button>)}</div>}{cursor && <button className="small-button native-load-more" onClick={() => load(true)} disabled={loading}>{loading ? 'Loading…' : 'Load more'}</button>}</>}
    {selected && <div className="native-task-detail" role="region" aria-label="Task summary"><button className="icon-btn" aria-label="Close task summary" onClick={() => setSelected(null)}><X size={16} /></button><span className="usage-kicker">READ-ONLY TASK SUMMARY</span><h3>{selected.title || 'Untitled task'}</h3><p>{selected.summary || 'Summary not reported.'}</p><dl><div><dt>Project</dt><dd>{selected.project || 'Not reported'}</dd></div><div><dt>Status</dt><dd>{selected.status || 'Not reported'}</dd></div><div><dt>Source</dt><dd>{selected.source || 'Not reported'}</dd></div></dl></div>}
  </section>;
}
