import React, {useMemo, useState} from 'react';
import {MessageCircle, Pause, Play, ArrowUpRight, Users, Radio, X} from 'lucide-react';
import {sceneFrameBufs, type OfficeCharacterName} from '../vendor/munder-office/portraitArt';
import './office-view.css';

type Agent={id:string;name:string;role:string;model:string;status:string;statusLabel:string;isSupervisor:boolean;delegated?:boolean;conversation?:boolean;observed:boolean;stale:boolean;reportsTo?:string;assignment?:string;task?:{id:string;title:string;status:string}};
type Msg={id:string;from:string;to:string;text:string;createdAt?:string;state:string};
type Props={agents:Agent[];messages:Msg[];title:string;connected:boolean;example:boolean;onContact:(id:string)=>void;onTask:(id:string)=>void;onChat:()=>void;onExample:()=>void};
const presets:OfficeCharacterName[]=['jim','pam','dwight','kelly','oscar','angela','kevin','phyllis','andy','stanley','ryan','toby'];
const spriteCache=new Map<string,string>();
function sprite(id:string,supervisor:boolean){
 const name=supervisor?'michael':presets[Array.from(id).reduce((n,c)=>(n*31+c.charCodeAt(0))>>>0,0)%presets.length];
 if(spriteCache.has(name))return spriteCache.get(name)!;
 const c=document.createElement('canvas');c.width=18;c.height=32;const ctx=c.getContext('2d');if(!ctx)return '';
 const data=ctx.createImageData(18,32);data.data.set(sceneFrameBufs(name).front[0]);ctx.putImageData(data,0,0);
 const url=c.toDataURL();spriteCache.set(name,url);return url;
}
function Plant({x,y}:{x:number;y:number}){return <g transform={`translate(${x} ${y})`}><ellipse cy="15" rx="21" ry="8" fill="#51362e" opacity=".2"/><path d="M-12-3H12L9 15H-9Z" fill="#b57958"/><path d="M0 1V-29M0-8Q-30-41-19-44Q5-45 0-8M1-18Q27-45 24-25Q21-4 1-6" stroke="#477759" strokeWidth="5" fill="#679064"/><path d="M-1-20Q-9-57 4-53Q18-43-1-20" fill="#7f9b60"/></g>}
function Floor(){return <svg className="office-scenery" viewBox="0 0 1000 570" aria-hidden="true"><defs><pattern id="hq-floor" width="140" height="50" patternUnits="userSpaceOnUse"><path d="M0 0H140V50H0Z" fill="#d7b795"/><path d="M0 0H140M0 50H140M70 0V25M0 25H140M25 25V50" stroke="#b9947045"/><path d="M10 12H50M90 36H126" stroke="#ecd4b4" opacity=".45"/></pattern><linearGradient id="hq-wall" x2="0" y2="1"><stop stopColor="#f5eddb"/><stop offset="1" stopColor="#daceba"/></linearGradient></defs><path d="M35 58L965 58V514L929 552H70L35 514Z" fill="#4c3d37"/><path d="M35 58H965V500L930 534H70L35 500Z" fill="url(#hq-floor)"/><path d="M35 58H965V128H35Z" fill="url(#hq-wall)"/><path d="M35 58L60 86V513L35 500Z" fill="#b9a68e"/><path d="M965 58L940 86V520L965 500Z" fill="#c3b198"/><path d="M60 127H940" stroke="#918169" strokeWidth="9"/>
 <g fill="#b8d8d0" stroke="#e7e1d4" strokeWidth="7"><path d="M102 71H211V117H102Z"/><path d="M249 71H358V117H249Z"/><path d="M399 71H508V117H399Z"/></g><g stroke="#ffffff88" strokeWidth="2"><path d="M159 73V115M300 73V115M454 73V115"/></g>
 <rect x="685" y="148" width="223" height="180" rx="8" fill="#84948d" opacity=".34"/><path d="M670 128V348H929M670 128H930" stroke="#567777" strokeWidth="8" fill="none"/><path d="M674 132H930V337H674Z" fill="#d0e5df" opacity=".27"/><path d="M792 132V337M675 228H930" stroke="#64827c" strokeWidth="4" fill="none" opacity=".65"/>
 <rect x="93" y="398" width="230" height="99" rx="40" fill="#c8867266"/><rect x="109" y="414" width="194" height="66" rx="28" fill="none" stroke="#f1d0ab" strokeWidth="2"/>
 <g fill="#798b78" stroke="#5b6e5c" strokeWidth="3"><rect x="109" y="430" width="67" height="45" rx="7"/><rect x="234" y="430" width="67" height="45" rx="7"/></g><ellipse cx="204" cy="443" rx="32" ry="21" fill="#725a47"/><ellipse cx="204" cy="438" rx="32" ry="21" fill="#e4d3ac"/><rect x="193" y="427" width="20" height="14" rx="2" fill="#c6a796"/>
 <g transform="translate(724 414)"><path d="M0 0H130V65H0Z" fill="#7c624e"/><path d="M6 5H124V27H6ZM6 33H124V57H6Z" fill="#51483e"/>{[9,22,34,48,61,79,91,107].map((x,i)=><rect key={x} x={x} y={i%2?6:34} width="9" height="20" fill={['#b98471','#d7c389','#74938a'][i%3]}/>)}</g>
 <Plant x={87} y={170}/><Plant x={604} y={165}/><Plant x={910} y={457}/><Plant x={620} y={482}/>
 <text x="791" y="106" textAnchor="middle" fontSize="13" letterSpacing="3" fill="#675e50">DIRECTION &amp; REVIEW</text><text x="102" y="364" fontSize="12" letterSpacing="3" fill="#7e6755">THE TEAM FLOOR</text>
 </svg>}
export default function OfficeView({agents,messages,title,connected,example,onContact,onTask,onChat,onExample}:Props){
 const [selectedId,setSelectedId]=useState(''),[paused,setPaused]=useState(false);
 const selected=agents.find(a=>a.id===selectedId);
 const shown=useMemo(()=>[...agents.filter(a=>a.isSupervisor),...agents.filter(a=>!a.isSupervisor)].slice(0,12),[agents]);
 const working=agents.filter(a=>a.status==='working').length;
 const label=(id:string)=>agents.find(a=>a.id===id)?.name||id;
 return <section className={`office-view ${paused?'office-paused':''}`} aria-label={example?'Example office':'Team office'}>
 <header className="office-heading"><div><span className="office-eyebrow"><span className={connected&&!example?'office-online':''}/>{example?'Example office · no model calls':connected?'Connected workspace':'Your workspace'}</span><h2>{title}</h2><p>{example?'Explore the roles. This preview does not start agents.':'A place to see who is working, what they own, and where to help.'}</p></div><button className="small-button" aria-pressed={paused} onClick={()=>setPaused(!paused)}>{paused?<Play size={14}/>:<Pause size={14}/>}<span>{paused?'Resume motion':'Pause motion'}</span></button></header>
 <div className="office-layout"><div className="office-scene-panel"><div className="office-scene-scroll" tabIndex={0} aria-label="Office floor"><div className="office-scene"><Floor/>{shown.map((a,i)=>{
 const workerIndex=shown.slice(0,i).filter(x=>!x.isSupervisor).length;
 const left=a.isSupervisor?79:19+(workerIndex%4)*14.5;
 const top=a.isSupervisor?35:workerIndex<4?37:workerIndex<8?58:81;
 return <button key={a.id} className={`office-desk ${a.status} ${selectedId===a.id?'selected':''}`} style={{left:left+'%',top:top+'%'}} aria-label={`Inspect ${a.name}`} aria-pressed={selectedId===a.id} onClick={()=>setSelectedId(a.id)}><span className="desk-shadow"/><span className="desk-surface"><span className="desk-monitor"><i/><i/><i/></span><span className="desk-keyboard"/><span className="desk-cup"/></span><img className="office-person" src={sprite(a.id,a.isSupervisor)} alt=""/><span className="desk-nameplate"><b>{a.name}</b><small><i/>{a.statusLabel}</small></span></button>;
 })}{!agents.length&&<div className="office-welcome"><span className="office-welcome-icon"><Users size={26}/></span><h3>Your office is ready</h3><p>Start with an idea. Your supervisor brings in teammates when the work needs them.</p><button className="primary-button" onClick={onChat}><MessageCircle size={16}/>Talk to supervisor</button><button className="office-preview" onClick={onExample}>Explore an example <ArrowUpRight size={14}/></button></div>}</div></div><footer className="office-floor-footer"><span><Users size={14}/>{example?'6 example roles':`${agents.length} ${agents.length===1?'teammate':'teammates'}`}</span><span>{example?'Illustrative activity':working?`${working} working · native status`:'No work observed in progress'}</span>{agents.length>12&&<span>All {agents.length} available in the roster</span>}</footer></div>
 <aside className="office-inspector" aria-label="Teammate details">{selected?<><div className="office-inspector-top"><span className="office-eyebrow">{selected.delegated?'DELEGATED ASSIGNMENT':selected.isSupervisor?'YOUR SUPERVISOR':'TEAMMATE'}</span><button className="icon-btn" aria-label="Close teammate details" onClick={()=>setSelectedId('')}><X size={16}/></button></div><div className="office-portrait"><img src={sprite(selected.id,selected.isSupervisor)} alt=""/></div><h3>{selected.name}</h3><p className="office-role">{selected.role}</p><span className={`office-status ${selected.status}`}>{selected.statusLabel}</span><dl><dt>Model</dt><dd>{selected.model||'Not reported'}</dd><dt>Reports to</dt><dd>{selected.reportsTo?label(selected.reportsTo):selected.isSupervisor?'You':'Not reported'}</dd><dt>Assignment</dt><dd>{selected.task?<button className="office-task-link" onClick={()=>onTask(selected.task!.id)}>{selected.task.title}<ArrowUpRight size={14}/></button>:selected.assignment?<span className="office-assignment">{selected.assignment}</span>:'No recorded assignment'}</dd></dl><button className="primary-button" onClick={()=>onContact(selected.id)}><MessageCircle size={15}/>{example?'Try a real conversation':selected.delegated?'Talk to builder':selected.isSupervisor?'Talk to supervisor':selected.conversation?'Open teammate chat':selected.observed?'Talk to teammate':'Open recorded inbox'}</button><p className="office-small-note">{example?'These roles are examples, not running agents.':selected.stale?'Reconnect or refresh to verify this teammate’s current state.':selected.conversation?'This is a separate project conversation. Its status comes from that chat’s provider runtime; opening it does not start a new turn.':selected.observed?(selected.isSupervisor?'Your main project conversation is with this supervisor. It delegates to leads and specialists when the connected runtime supports teams.':'Opens a focused conversation beneath the office. Status and replies come from the native runtime.'):'This role is recorded. Execution has not been observed. Opening it shows the recorded inbox, not a live conversation.'}</p></>:<div className="office-inspector-empty"><Radio size={27}/><h3>Meet your team</h3><p>Select a desk to see its role, model, assignment and reporting line.</p><div className="office-role-flow"><b>You</b><span>↓</span><b>Supervisor</b><span>↓</span><b>Leads & specialists</b></div><p>One conversation for direction. Individual teammates for a focused follow-up.</p></div>}</aside></div>
 {!!agents.length&&<div className="office-roster" aria-label="Team roster">{agents.map(a=><button key={a.id} className={selectedId===a.id?'selected':''} aria-pressed={selectedId===a.id} onClick={()=>setSelectedId(a.id)}><img src={sprite(a.id,a.isSupervisor)} alt=""/><span><b>{a.name}</b><small>{a.role}</small></span><i className={a.status}/></button>)}</div>}
 {!!messages.length&&<div className="office-messages"><h3>Recent direction</h3>{messages.slice(-3).map(m=><article key={m.id}><MessageCircle size={16}/><div><b>{label(m.from)} → {label(m.to)}</b><p>{m.text}</p><small>{m.state==='accepted'?'Submitted · receipt not confirmed':m.state}</small></div></article>)}</div>}
 </section>;
}
