import React, {useEffect, useRef, useState} from 'react';
import {ArrowUp, ChevronRight, Code2, File, Folder, RefreshCw, Save, Terminal} from 'lucide-react';
import './project-files.css';
type Data = Record<string, any>;
async function api(url:string, body?:Data){const r=await fetch(url,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:undefined);const v=await r.json();if(!r.ok)throw Error(v.error||'The project operation failed.');return v}

export default function ProjectFiles({team,runtime,demo}:{team:string;runtime:Data;demo:boolean}){
  const [folder,setFolder]=useState('.'),[items,setItems]=useState<Data[]>([]),[file,setFile]=useState<Data|null>(null),[text,setText]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const [command,setCommand]=useState(''),[result,setResult]=useState<Data|null>(null),[terminal,setTerminal]=useState(false);
  const request=useRef(0), selected=useRef(team);selected.current=team;
  const base=`/api/files/${encodeURIComponent(team)}`;
  const dirty=file&&text!==file.text;
  async function browse(path:string){const seq=++request.current;try{const data=await api(`${base}?path=${encodeURIComponent(path)}`);if(seq===request.current){setFolder(data.path);setItems(data.items);setError('')}}catch(e:any){if(seq===request.current)setError(e.message)}}
  useEffect(()=>{setFile(null);setText('');setResult(null);setError('');browse('.');return()=>{request.current++}},[team]);
  async function open(item:Data,discard=false){if(dirty&&!discard){setError('Save or reload your current file before opening another.');return}if(item.kind==='folder'){browse(item.path);return}const seq=++request.current;try{const data=await api(`${base}?kind=file&path=${encodeURIComponent(item.path)}`);if(seq===request.current){setFile(data);setText(data.text);setError('')}}catch(e:any){if(seq===request.current)setError(e.message)}}
  async function save(){if(!file)return;const target=team;setBusy(true);try{const data=await api(base,{path:file.path,text,revision:file.revision});if(selected.current===target){setFile(data);setText(data.text);setError('')}}catch(e:any){if(selected.current===target)setError(e.message)}finally{setBusy(false)}}
  async function run(event:React.FormEvent){event.preventDefault();const target=team;setBusy(true);setResult(null);try{const data=await api(`/api/runtime/${encodeURIComponent(team)}/command`,{command});if(selected.current===target){setResult(data);setError('')}}catch(e:any){if(selected.current===target)setError(e.message)}finally{setBusy(false)}}
  return <div className="project-files"><header className="files-heading"><div><span className="usage-kicker">YOUR WORKSPACE</span><h2>Files & terminal</h2><p>Inspect the work, make a small edit, or run a check.</p></div><button className="small-button" onClick={()=>setTerminal(v=>!v)}><Terminal size={15}/>{terminal?'Hide terminal':'Open terminal'}</button></header>
    {error&&<p className="files-error" role="alert">{error}</p>}
    <div className="files-body"><aside className="file-tree"><header><button className="icon-btn" aria-label="Parent folder" disabled={folder==='.'} onClick={()=>browse(folder.includes('/')?folder.slice(0,folder.lastIndexOf('/')):'.')}><ArrowUp size={14}/></button><span>{folder==='.'?'Project':folder}</span><button className="icon-btn" aria-label="Refresh folder" onClick={()=>browse(folder)}><RefreshCw size={14}/></button></header>{items.map(item=><button className={file?.path===item.path?'selected':''} key={item.path} onClick={()=>open(item)}>{item.kind==='folder'?<Folder size={15}/>:<File size={15}/>}<span>{item.name}</span>{item.kind==='folder'&&<ChevronRight size={12}/>}</button>)}{!items.length&&<p>This folder is empty.</p>}</aside>
      <section className="file-editor">{file?<><header><Code2 size={15}/><span>{file.path}{dirty?' •':''}</span><button className="small-button" onClick={()=>open({path:file.path,kind:'file'},true)} disabled={busy}>Discard edits</button><button className="primary-button" onClick={save} disabled={!dirty||busy||demo||runtime.mode!=='execute'}><Save size={14}/>Save</button></header><textarea aria-label={`Edit ${file.path}`} spellCheck={false} value={text} onChange={e=>setText(e.target.value)} readOnly={demo||runtime.mode!=='execute'}/>{runtime.mode!=='execute'&&<p className="editor-hint">Files are read-only during planning. Start workspace execution to edit.</p>}</>:<div className="files-empty"><Code2 size={30}/><h3>Your work lives here</h3><p>Choose a file to inspect it. The editor stays inside this chat’s project.</p></div>}</section></div>
    {terminal&&<section className="project-terminal"><header><Terminal size={15}/>Project terminal<span>{runtime.accessMode==='full'?'Full access':runtime.mode==='execute'?'Workspace access':'Read-only'}</span></header><form onSubmit={run}><span>›</span><input aria-label="Terminal command" value={command} onChange={e=>setCommand(e.target.value)} placeholder="Run a command in this project…" maxLength={8000}/><button className="small-button" disabled={busy||demo||!runtime.connected||!command.trim()}>{busy?'Running…':'Run'}</button></form>{!runtime.connected&&<p>Send a chat message to connect the native runtime first.</p>}{result&&<><pre>{result.output||'(No output)'}</pre><footer>Exit {result.exitCode}{result.evidenceId?` · Evidence ${result.evidenceId}`:''}{result.truncated?' · Output limited':''}</footer></>}</section>}
  </div>
}
