import React from 'react';
import { ChevronDown, CircleAlert, Puzzle, RefreshCw, Search, Wrench } from 'lucide-react';
import './runtime-tools.css';

type Server = { name: string; authStatus?: string; runtimeStatus?: string; tools?: string[]; toolsError?: boolean };
type App = { id: string; name: string; enabled?: boolean; callable?: boolean };
type Skill = { name: string; description?: string; enabled?: boolean };
type Inventory = { checkedAt?: string; servers?: Server[]; apps?: App[]; skills?: Skill[]; errors?: { source?: string; message?: string }[]; truncated?: boolean; roleLibrary?: { count?: number; available?: boolean; description?: string } };

function browserExposure(data?: Inventory) { const matcher = /browser|cua|playwright|computer/i; return Boolean(data?.servers?.some(server => server.runtimeStatus === 'connected' && !server.toolsError && (matcher.test(server.name) || (server.tools || []).some(tool => matcher.test(tool))))); }
function DetailList({ title, children, count }: { title: string; children: React.ReactNode; count: number }) { return <details className="runtime-tool-details"><summary><span>{title}</span><b>{count}</b><ChevronDown size={14} /></summary>{children}</details>; }

export default function RuntimeTools({ team, connected }: { team?: string; connected?: boolean }) {
  const [data, setData] = React.useState<Inventory | null>(null); const [loading, setLoading] = React.useState(false); const [error, setError] = React.useState(''); const [query, setQuery] = React.useState(''); const [notice,setNotice]=React.useState(''); const [signIn,setSignIn]=React.useState(''); const request = React.useRef(0);
  React.useEffect(() => { request.current += 1; setData(null); setError(''); setQuery(''); setNotice(''); setSignIn(''); setLoading(false); }, [team, connected]);
  async function check() { if (!team || !connected) return; const current = ++request.current; setLoading(true); setError(''); try { const response = await fetch(`/api/runtime/${encodeURIComponent(team)}/tools`); const value = await response.json().catch(() => ({})); if (!response.ok) throw Error(value.error || 'Runtime tools could not be checked.'); if (current === request.current) setData(value); } catch { if (current === request.current) { setData(null); setError('Runtime tools could not be checked. Try again from this connected chat.'); } } finally { if (current === request.current) setLoading(false); } }
  async function change(action:string,name:string,enabled?:boolean){const current=++request.current;setLoading(true);setError('');setSignIn('');try{const r=await fetch(`/api/runtime/${encodeURIComponent(team||'')}/tool-action`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,name,...(enabled===undefined?{}:{enabled})})});const value=await r.json();if(!r.ok)throw Error(value.error||'The runtime could not change this setting.');if(current!==request.current)return;setNotice(value.message||'Updated.');if(value.authorizationUrl)setSignIn(value.authorizationUrl);else await check()}catch(e:any){if(current===request.current)setError(e.message)}finally{if(current===request.current)setLoading(false)}}
  const needle = query.trim().toLowerCase(); const matches = (value: string) => !needle || value.toLowerCase().includes(needle);
  const servers = (data?.servers || []).filter(server => matches(server.name) || (server.tools || []).some(matches)); const apps = (data?.apps || []).filter(app => matches(app.name) || matches(app.id)); const skills = (data?.skills || []).filter(skill => matches(skill.name) || matches(skill.description || ''));
  const availableServers = (data?.servers || []).filter(server => server.runtimeStatus === 'connected').length;
  return <section className="runtime-tools" aria-label="Skills and tools"><header><div><span className="usage-kicker">RUNTIME INVENTORY</span><h2>Skills &amp; tools</h2><p>Availability shows what this connected runtime exposes. It does not prove a tool call succeeded.</p></div><button className="small-button" onClick={check} disabled={!team || !connected || loading}><RefreshCw size={14} className={loading ? 'refreshing' : ''} />{loading ? 'Checking…' : 'Check runtime tools'}</button></header>
    {!connected || !team ? <p className="runtime-tools-empty">Send a message first to connect this chat, then check the runtime tools it exposes.</p> : <>{notice&&<p role="status">{notice}{signIn&&<> <a href={signIn} target="_blank" rel="noopener noreferrer">Continue sign-in</a></>}</p>}{error && <div className="runtime-tools-errors" role="alert"><CircleAlert size={14} />{error}</div>}{data && <><div className="runtime-tool-summary"><article><Wrench size={16} /><b>{availableServers} / {data.servers?.length || 0}</b><span>runtime servers available</span></article><article><Puzzle size={16} /><b>{data.apps?.filter(app => app.callable).length || 0}</b><span>apps verified callable</span></article><article><b>{data.skills?.filter(skill => skill.enabled).length || 0}</b><span>skills enabled</span></article><article><b>{browserExposure(data) ? 'Exposed by runtime' : 'Not exposed here'}</b><span>browser control in MCP scope</span></article></div><label className="runtime-tool-search"><Search size={14} /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Filter by name" aria-label="Filter skills and tools" /></label><div className="runtime-tool-lists"><DetailList title="Runtime servers" count={servers.length}><ul>{servers.map(server => <li key={server.name}><b>{server.name}</b><span>{server.runtimeStatus || 'Status not reported'}{server.authStatus ? ` · ${server.authStatus}` : ''}</span>{server.authStatus==='notLoggedIn'&&<button className="small-button" disabled={loading} onClick={()=>change('sign-in',server.name)}>Connect</button>}{server.toolsError ? <small>Tool list was not reported.</small> : server.tools?.length ? <small>{server.tools.join(' · ')}</small> : <small>No tools reported.</small>}</li>) || null}</ul></DetailList><DetailList title="Plugin apps" count={apps.length}><ul>{apps.map(app => <li key={app.id}><b>{app.name}</b><span>{app.callable ? 'Runtime verified callable' : app.enabled ? 'Enabled; callable status not reported' : 'Not enabled'}</span></li>)}</ul></DetailList><DetailList title="Skills" count={skills.length}><ul>{skills.map(skill => <li key={skill.name}><b>{skill.name}</b><span>{skill.enabled ? 'Enabled' : 'Not enabled'}</span><small>{skill.description || 'Description not reported.'}</small><button className="small-button" disabled={loading} onClick={()=>change('skill',skill.name,!skill.enabled)}>{skill.enabled?'Disable':'Enable'} in Codex</button></li>)}</ul></DetailList></div>{data.roleLibrary && <p className="runtime-role-library">Role library: {data.roleLibrary.available ? `${data.roleLibrary.count || 0} available` : 'Not reported'}{data.roleLibrary.description ? ` · ${data.roleLibrary.description}` : ''}</p>}{data.truncated && <p className="runtime-role-library">Lists are limited by the runtime response.</p>}{data.errors?.length ? <div className="runtime-tools-errors" role="status"><CircleAlert size={14} />Some runtime inventory details were not reported.</div> : null}</>}</>}</section>;
}
