import React,{useEffect,useState,useRef} from 'react';
import {Bot,ChevronRight,MessageSquare,RefreshCw,Send,Square} from 'lucide-react';
import './workers-panel.css';
type Data=Record<string,any>;
export default function WorkersPanel({team,connected,onData,selectedThread}:{team:string;connected:boolean;onData?:(value:Data)=>void;selectedThread?:string}){
  const [data,setData]=useState<Data>({workers:[]}),[error,setError]=useState(''),[busy,setBusy]=useState(false),[selected,setSelected]=useState(''),[message,setMessage]=useState(''),[receipt,setReceipt]=useState('');
  const generation=useRef(0);
  useEffect(()=>{generation.current++;setData({workers:[]});setSelected('');setReceipt('');setError('');void refresh();const timer=setInterval(()=>{if(connected)void refresh()},30000);return()=>{generation.current++;clearInterval(timer)}},[team,connected]);
  useEffect(()=>{if(selectedThread)setSelected(selectedThread)},[selectedThread]);
  async function call(action:string,body?:Data){const r=await fetch(`/api/runtime/${encodeURIComponent(team)}/${action}`,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:undefined);const value=await r.json();if(!r.ok)throw Error(value.error||'Worker operation failed.');return value}
  async function refresh(){const current=generation.current;setBusy(true);try{const value=await call('workers');if(current!==generation.current)return;setData(value);onData?.(value);setError('')}catch(e:any){if(current===generation.current)setError(e.message)}finally{if(current===generation.current)setBusy(false)}}
  async function send(e:React.FormEvent){e.preventDefault();setBusy(true);try{const r=await call('worker-message',{threadId:selected,prompt:message});setMessage('');setReceipt(`Submitted to the native worker (${r.mode==='turn/steer'?'active work updated':'worker continued'}). Its next response confirms progress.`);setError('')}catch(e:any){setError(e.message)}finally{setBusy(false)}}
  async function stop(){setBusy(true);try{const r=await call('stop-workers',{});setReceipt(`${r.results.filter((x:Data)=>x.status==='stopRequested').length} stop requests sent. Refresh to check which workers stopped.`);setError('')}catch(e:any){setError(e.message)}finally{setBusy(false)}}
  const workers=data.workers||[];
  const label=(id:string)=>workers.find((w:Data)=>w.threadId===id)?.nickname||workers.find((w:Data)=>w.threadId===id)?.role||'Supervisor';
  return <section className="workers-panel"><header><div><span className="usage-kicker">LIVE RUNTIME</span><h3>Talk to your team</h3><p>Check actual workers, give direction, and follow their progress.</p></div><button className="small-button" disabled={!connected||busy} onClick={refresh}><RefreshCw size={14}/>Refresh workers</button></header>
  {error&&<p role="alert" className="workers-error">{error}</p>}{receipt&&<p role="status" className="workers-receipt">{receipt}</p>}
  {!workers.length?<p className="workers-empty">{connected?'Workers appear after the supervisor delegates. Refresh to read the native roster.':'Connect this chat to see its active team.'}</p>:<><div className="worker-cards">{workers.map((w:Data)=><button key={w.threadId} className={selected===w.threadId?'selected':''} onClick={()=>{setSelected(w.threadId);setReceipt('')}}><span className="worker-avatar"><Bot size={20}/></span><span><b>{w.nickname||w.role||'Worker'}</b><small>{w.model||'Model not reported'}</small>{typeof w.usageSummary?.totalTokens==='number'&&<small>{w.usageSummary.totalTokens.toLocaleString()} reported tokens · individual allowance not reported</small>}<small>{label(w.parentThreadId)}<ChevronRight size={11}/>{w.role||'Specialist'}</small></span><i className={`worker-state ${w.status}`}>{w.stale?'Needs refresh':w.status||'Unknown'}</i></button>)}</div><div className="workers-actions"><button className="small-button" onClick={stop} disabled={busy||!connected}><Square size={12}/>Stop observed workers</button>{!data.complete&&<small>Some descendants could not be verified.</small>}</div></>}
  {selected&&<form className="worker-message" onSubmit={send}><label><MessageSquare size={15}/>Direction for {label(selected)}<textarea aria-label="Message native worker" value={message} onChange={e=>setMessage(e.target.value)} placeholder="Add a constraint, clarify a task, or ask for an update…" maxLength={12000}/></label><button className="primary-button" disabled={!connected||busy||!message.trim()}><Send size={14}/>Send to worker</button></form>}
  </section>
}
